name: RISC-V riscv-gnu-toolchain

runs:
  using: composite
  steps:
    - id: cache-riscv-gnu-toolchain
      uses: actions/cache@v3
      with:
        path: .riscv-gnu-toolchain
        key: riscv-gnu-toolchain-${{ runner.os }}

    - shell: bash
      if: steps.cache-riscv-gnu-toolchain.outputs.cache-hit != 'true'
      run: |
        mkdir -p .riscv-gnu-toolchain
        cd .riscv-gnu-toolchain
        wget -q -O - https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2025.11.21/riscv32-elf-ubuntu-24.04-gcc.tar.xz | tar -Jx --transform "s/riscv/riscv32/"
        cd ..

    - shell: bash
      run: |
        echo "$(pwd)/.riscv-gnu-toolchain/riscv32/bin" >> $GITHUB_PATH


